name: macOS Xcode Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build using Xcode
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set Xcode version (optional)
      run: sudo xcode-select -s /Applications/Xcode.app

    - name: Build with xcodebuild
      run: |
        xcodebuild \
          -project HyperTune.xcodeproj \
          -scheme HyperTune \
          -configuration Release \
          clean build

    - name: Archive the build (optional)
      run: |
        xcodebuild \
          -project HyperTune.xcodeproj \
          -scheme HyperTune \
          -configuration Release \
          -archivePath build/HyperTune.xcarchive \
          archive
